### ISSUE TITLE
Problem with docker-compose

### ISSUE THREAD

**Issue by LEv145** [eikowagenknecht/lootscraper#101] opened 2022-09-29 16:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error when building docker image

### Steps To Reproduce

docker-compose.yml:
```yaml
version: "3.9"

services:
    lootscraper:
        image: eikowagenknecht/lootscraper:latest
```
1) docker compose up

Log:
```py
rss-server-lootscraper-1  | 2022-09-29 16:21:26,927 alembic.runtime.migration [INFO ] Running upgrade d0cab9037616 -> 8267b60db582, Datetime
rss-server-lootscraper-1  | Traceback (most recent call last):
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
rss-server-lootscraper-1  |     self.dialect.do_execute(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
rss-server-lootscraper-1  |     cursor.execute(statement, parameters)
rss-server-lootscraper-1  | sqlite3.OperationalError: near "DROP": syntax error
rss-server-lootscraper-1  | 
rss-server-lootscraper-1  | The above exception was the direct cause of the following exception:
rss-server-lootscraper-1  | 
rss-server-lootscraper-1  | Traceback (most recent call last):
rss-server-lootscraper-1  |   File "/app/lootscraper.py", line 463, in <module>
rss-server-lootscraper-1  |     main()
rss-server-lootscraper-1  |   File "/app/lootscraper.py", line 51, in main
rss-server-lootscraper-1  |     run_main_loop()
rss-server-lootscraper-1  |   File "/app/lootscraper.py", line 104, in run_main_loop
rss-server-lootscraper-1  |     db = stack.enter_context(LootDatabase(echo=Config.get().db_echo))
rss-server-lootscraper-1  |   File "/app/app/sqlalchemy.py", line 246, in __init__
rss-server-lootscraper-1  |     self.initialize_or_update()
rss-server-lootscraper-1  |   File "/app/app/sqlalchemy.py", line 279, in initialize_or_update
rss-server-lootscraper-1  |     command.upgrade(alembic_cfg, "head")
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
rss-server-lootscraper-1  |     script.run_env()
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
rss-server-lootscraper-1  |     util.load_python_file(self.dir, "env.py")
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
rss-server-lootscraper-1  |     module = load_module_py(module_id, path)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
rss-server-lootscraper-1  |     spec.loader.exec_module(module)  # type: ignore
rss-server-lootscraper-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
rss-server-lootscraper-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
rss-server-lootscraper-1  |   File "/app/alembic/env.py", line 116, in <module>
rss-server-lootscraper-1  |     run_migrations_online()
rss-server-lootscraper-1  |   File "/app/alembic/env.py", line 110, in run_migrations_online
rss-server-lootscraper-1  |     context.run_migrations()
rss-server-lootscraper-1  |   File "<string>", line 8, in run_migrations
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
rss-server-lootscraper-1  |     self.get_context().run_migrations(**kw)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
rss-server-lootscraper-1  |     step.migration_fn(**kw)
rss-server-lootscraper-1  |   File "/app/alembic/versions/20220414_195921_datetime.py", line 70, in upgrade
rss-server-lootscraper-1  |     op.drop_column("loot", "seen_first")
rss-server-lootscraper-1  |   File "<string>", line 8, in drop_column
rss-server-lootscraper-1  |   File "<string>", line 3, in drop_column
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/ops.py", line 2189, in drop_column
rss-server-lootscraper-1  |     return operations.invoke(op)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/base.py", line 399, in invoke
rss-server-lootscraper-1  |     return fn(self, operation)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 89, in drop_column
rss-server-lootscraper-1  |     operations.impl.drop_column(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 331, in drop_column
rss-server-lootscraper-1  |     self._exec(base.DropColumn(table_name, column, schema=schema))
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 195, in _exec
rss-server-lootscraper-1  |     return conn.execute(construct, multiparams)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
rss-server-lootscraper-1  |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
rss-server-lootscraper-1  |     return connection._execute_ddl(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
rss-server-lootscraper-1  |     ret = self._execute_context(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
rss-server-lootscraper-1  |     self._handle_dbapi_exception(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
rss-server-lootscraper-1  |     util.raise_(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
rss-server-lootscraper-1  |     raise exception
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
rss-server-lootscraper-1  |     self.dialect.do_execute(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
rss-server-lootscraper-1  |     cursor.execute(statement, parameters)
rss-server-lootscraper-1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "DROP": syntax error
rss-server-lootscraper-1  | [SQL: ALTER TABLE loot DROP COLUMN seen_first]
rss-server-lootscraper-1  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
rss-server-lootscraper-1 exited with code 1
```

**Comment by eikowagenknecht** [comment] 2022-09-30 18:48
Seems to be an error with the db migration script for new installs. I'll have a look at it.

**Comment by eikowagenknecht** [comment] 2022-09-30 19:34
Nope, the error was in a later stage (fixed with #102). Interesting error. I can reproduce with docker compose, on my local system it works for a new db, though. Investigating further..

**Comment by eikowagenknecht** [comment] 2022-09-30 20:24
Apparently the "DROP" command executed just fine in a Windows environment where the Linux docker environment needed it to be in a batch op... should work now in the `main` branch. `latest` will follow in a few minutes.

**Closed by eikowagenknecht** 2022-09-30 20:24 UTC
Labels: bug

**Comment by LEv145** [comment] 2022-10-01 12:03
Other problem:
```py
rss-server-lootscraper-1  | Invalid developer chat ID. Only ignore if you don't use the Telegram bot.
rss-server-lootscraper-1  | Invalid telegram admin ID. Only ignore if you don't use the Telegram bot.
rss-server-lootscraper-1  | Using virtual display
rss-server-lootscraper-1  | 2022-10-01 12:02:52,297 root [INFO ] Starting LootScraper v0.4.6
rss-server-lootscraper-1  | 2022-10-01 12:02:52,297 app.sqlalchemy [INFO ] Running database migrations
rss-server-lootscraper-1  | 2022-10-01 12:02:52,313 alembic.runtime.migration [INFO ] Context impl SQLiteImpl.
rss-server-lootscraper-1  | 2022-10-01 12:02:52,313 alembic.runtime.migration [INFO ] Will assume non-transactional DDL.
rss-server-lootscraper-1  | 2022-10-01 12:02:52,349 alembic.runtime.migration [INFO ] Running upgrade d0cab9037616 -> 8267b60db582, Datetime
rss-server-lootscraper-1  | Traceback (most recent call last):
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
rss-server-lootscraper-1  |     self.dialect.do_execute(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
rss-server-lootscraper-1  |     cursor.execute(statement, parameters)
rss-server-lootscraper-1  | sqlite3.OperationalError: duplicate column name: seen_first_tmp
rss-server-lootscraper-1  | 
rss-server-lootscraper-1  | The above exception was the direct cause of the following exception:
rss-server-lootscraper-1  | 
rss-server-lootscraper-1  | Traceback (most recent call last):
rss-server-lootscraper-1  |   File "/app/lootscraper.py", line 463, in <module>
rss-server-lootscraper-1  |     main()
rss-server-lootscraper-1  |   File "/app/lootscraper.py", line 51, in main
rss-server-lootscraper-1  |     run_main_loop()
rss-server-lootscraper-1  |   File "/app/lootscraper.py", line 104, in run_main_loop
rss-server-lootscraper-1  |     db = stack.enter_context(LootDatabase(echo=Config.get().db_echo))
rss-server-lootscraper-1  |   File "/app/app/sqlalchemy.py", line 246, in __init__
rss-server-lootscraper-1  |     self.initialize_or_update()
rss-server-lootscraper-1  |   File "/app/app/sqlalchemy.py", line 279, in initialize_or_update
rss-server-lootscraper-1  |     command.upgrade(alembic_cfg, "head")
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 322, in upgrade
rss-server-lootscraper-1  |     script.run_env()
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
rss-server-lootscraper-1  |     util.load_python_file(self.dir, "env.py")
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
rss-server-lootscraper-1  |     module = load_module_py(module_id, path)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
rss-server-lootscraper-1  |     spec.loader.exec_module(module)  # type: ignore
rss-server-lootscraper-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
rss-server-lootscraper-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
rss-server-lootscraper-1  |   File "/app/alembic/env.py", line 116, in <module>
rss-server-lootscraper-1  |     run_migrations_online()
rss-server-lootscraper-1  |   File "/app/alembic/env.py", line 110, in run_migrations_online
rss-server-lootscraper-1  |     context.run_migrations()
rss-server-lootscraper-1  |   File "<string>", line 8, in run_migrations
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
rss-server-lootscraper-1  |     self.get_context().run_migrations(**kw)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 623, in run_migrations
rss-server-lootscraper-1  |     step.migration_fn(**kw)
rss-server-lootscraper-1  |   File "/app/alembic/versions/20220414_195921_datetime.py", line 45, in upgrade
rss-server-lootscraper-1  |     op.add_column("loot", sa.Column("seen_first_tmp", sa.DateTime(), nullable=True))
rss-server-lootscraper-1  |   File "<string>", line 8, in add_column
rss-server-lootscraper-1  |   File "<string>", line 3, in add_column
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/ops.py", line 2047, in add_column
rss-server-lootscraper-1  |     return operations.invoke(op)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/base.py", line 399, in invoke
rss-server-lootscraper-1  |     return fn(self, operation)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 154, in add_column
rss-server-lootscraper-1  |     operations.impl.add_column(table_name, column, schema=schema, **kw)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 322, in add_column
rss-server-lootscraper-1  |     self._exec(base.AddColumn(table_name, column, schema=schema))
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 195, in _exec
rss-server-lootscraper-1  |     return conn.execute(construct, multiparams)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
rss-server-lootscraper-1  |     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
rss-server-lootscraper-1  |     return connection._execute_ddl(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
rss-server-lootscraper-1  |     ret = self._execute_context(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
rss-server-lootscraper-1  |     self._handle_dbapi_exception(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
rss-server-lootscraper-1  |     util.raise_(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
rss-server-lootscraper-1  |     raise exception
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
rss-server-lootscraper-1  |     self.dialect.do_execute(
rss-server-lootscraper-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
rss-server-lootscraper-1  |     cursor.execute(statement, parameters)
rss-server-lootscraper-1  | sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: seen_first_tmp
rss-server-lootscraper-1  | [SQL: ALTER TABLE loot ADD COLUMN seen_first_tmp DATETIME]
rss-server-lootscraper-1  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
```
